### ISSUE TITLE
Python 3.9.0 update breaks borgbackup

### ISSUE THREAD

**Issue by michaeldonovan** [dmacias72/unRAID-NerdPack#33]
After updating Python to 3.9.0 and installing borg 1.1.14, running borg now causes an exception to be thrown. Looks like borg is still being installed under /usr/lib64/python3.8 so 3.9's pkg_resources can't find it.

Let me know if there's any additional information I can provide.

Thanks!

```
Traceback (most recent call last):
  File "/usr/bin/borg", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 3239, in <module>
    def _initialize_master_working_set():
  File "/usr/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/usr/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'borgbackup==1.1.14' distribution was not found and is required by the application
```

**Comment by dmacias72** [comment]
Recompiled with python 3.9 Should work now

**Comment by michaeldonovan** [comment]
Yep, it works now. Thanks for the quick turnaround!

**Comment by dmacias72** [comment]
And thank you.
