### ISSUE TITLE
iotop and ncurses compatible versions?

### ISSUE THREAD

**Issue by techie2000** [dmacias72/unRAID-NerdPack#59]
I previously used iotop without issue.
I came to use it the other day and got errors.
On taking a closer look today I have managed to avoid the errors by manually installing an older version of ncurses.

Errors observed running nerdpack version `iotop-0.6-x86_64-1_fs.tgz` and `ncurses-terminfo-6.1.20191130-x86_64-1.txz` :
```
Traceback (most recent call last):
  File "/usr/sbin/iotop", line 17, in <module>
    main()
  File "/usr/lib64/python2.7/site-packages/iotop/ui.py", line 620, in main
    main_loop()
  File "/usr/lib64/python2.7/site-packages/iotop/ui.py", line 610, in <lambda>
    main_loop = lambda: run_iotop(options)
  File "/usr/lib64/python2.7/site-packages/iotop/ui.py", line 508, in run_iotop
    return curses.wrapper(run_iotop_window, options)
  File "/usr/lib64/python2.7/curses/wrapper.py", line 22, in wrapper
    stdscr = curses.initscr()
  File "/usr/lib64/python2.7/curses/__init__.py", line 33, in initscr
    fd=_sys.__stdout__.fileno())
_curses.error: setupterm: could not find terminal
```
Installing version`https://slackware.uk/slackware/slackware64-14.2/slackware64/l/ncurses-5.9-x86_64-4.txz` returns iotop to operational status.

**Comment by techie2000** [comment]
Looking at [https://github.com/Tomas-M/iotop](https://github.com/Tomas-M/iotop) it would appear that the version of iotop in nerpack (0.6) is massively out of date, with v1.20 being releases very recently - and includes pretty graphs of each process. 

Could we get this version added?

**Comment by bitcoredotorg** [comment]
Hello @techie2000 , what commands did you issue to install the slackware ncurses version on undraid?
I am experiencing this issue as well, and I also echo your comments about the software being out of date.
Thank you all,

**Comment by matthew10199** [comment]
Having the same issue. iotop worked previously, however when I tried to use it today I received the error above.

**Comment by boomam** [comment]
Same issue here, too.

**Comment by boomam** [comment]
Quick and dirty fix (done for unraid communinty, so adapt as needed)
https://forums.unraid.net/topic/35866-unraid-6-nerdpack-cli-tools-iftop-iotop-screen-kbd-etc/?do=findComment&comment=1079739

````
cd /mnt/user/XXXX (where XXXX is a share of yours)

wget https://slackware.uk/slackware/slackware64-14.2/slackware64/l/ncurses-5.9-x86_64-4.txz

upgradepkg --install-new ncurses-5.9-x86_64-4.txz
````

**Comment by techie2000** [comment]
> Hello @techie2000 , what commands did you issue to install the slackware ncurses version on undraid? I am experiencing this issue as well, and I also echo your comments about the software being out of date. Thank you all,

@boomam has provided a solution to keep running the nerd version (0.6) of iotop (https://github.com/dmacias72/unRAID-NerdPack/issues/59#issuecomment-1003783782). 
For now, I'm keeping `ncurses-5.9-x86_64-4.txz` in `/boot/extra` so it's available when I need it (after each reboot) and without having to think why it's not working and how to resolve it.
Of course, one needs to take care that a newer version of ncurses is not required for some feature of core unraid in a future release...

I think it's probably a job for a wknd for me to recompile v1.20 on my box and keep that in my /boot/extra instead - best of both worlds - no downgrading of ncurses and newer/latest version of iotop :)
